### ISSUE TITLE
Maximum number of regions should be a processor constraint

### ISSUE THREAD

**Issue by plehegar** [w3c/imsc#11]
The requirement in chapter 4.6.3 [1] to limit the number of presented regions in a given intermediate synchronic document should be expressed as a minimal processing constraint rather than a maximal document constraint in order not to limit future expansion. Example wording:

Presentation processors SHALL be able to present 4 or more regions within any given intermediate synchronic document.

This would permit sub-profiling of IMSC in other environments such that more than 4 regions are permitted within an intermediate synchronic document if a use case for that should arise, while still ensuring that all documents authored to meet the maximum of 4 regions constraint can be successfully processed.

[1] http://www.w3.org/TR/ttml-imsc1/#maximum-number

This may require a processor profile to be created for IMSC1, as noted as a possibility in ISSUE-307.

(raised by Nigel Megitt on 2014-05-21)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/315

**Comment by nigelmegitt** [comment]
If we ever find a concrete use case for changing the number of regions to a larger number, we can do that in a future version of IMSC. Ideally that use case would be identified before we finalise IMSC 1.1, since it's better to make changes like this sooner rather than later, but since I cannot identify anything stronger than "align with the EBU-TT-D minimum processor region support recommendation" I'm going to close this for now.
