### ISSUE TITLE
Anamorphic font sizes?

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#175]
The feature #fontSize-anamorphic is prohibited; however, the initial font size is '1c', which may translate to an anamorphic font size.

If all anamorphic font sizes are intended to be prohibited, then the current language in insufficient.

**Comment by nigelmegitt** [comment]
My reading of this is that the TTML1 wording on [`tts:fontSize`](https://www.w3.org/TR/ttml1/#style-attribute-fontSize) applies:

> If a single `<length>` value is specified, then this length applies equally to horizontal and vertical scaling of a glyph's EM square;

which I interpret to be isomorphic font sizing.

Also the [`#fontSize-anamorphic`](https://www.w3.org/TR/ttml1/#feature-fontSize-anamorphic) feature clearly relates to the use of two length specifications rather than any computed actual font size, for example.

> A ... processor supports the `#fontSize-anamorphic` feature if it recognizes and is capable of transforming values of the `tts:fontSize` attribute that consist of two `<length>` specifications.

Given this wording, how can the value `"1c"` translate to an anamorphic font size, and what language would be needed to address it? I'm worried I've missed something now...

**Comment by skynavga** [comment]
Right, don't know why, but I was thinking '1c' was the same as '1c 1c'. You are correct that the former should apply cell height equally to font height and width, while the latter applies cell height to font height and cell width to font width, which may be anamorphic. I'm closing this.
