### ISSUE TITLE
First Pass at IMSC2 to CSS Fallback

### ISSUE THREAD

**Issue by dae-kim** [w3c/imsc#218]
To propose a fallback behavior re:
https://github.com/w3c/imsc/wiki/TTML2-features-for-inclusion-in-IMSC2

**Comment by dae-kim** [comment]
Fallback proposals:

fontShear -- ignore

ruby -- direct mapping to CSS

rubyAlign -- direct mapping to CSS except the values: auto, end, withBase. These values should be replaced with "space-around"

rubyPosition -- pending resolution to https://github.com/w3c/ttml2/issues/254

textEmphasis -- <emphasis-style> and <emphasis-color> have direct mapping to CSS. <emphasis-position> pending resolution to https://github.com/w3c/ttml2/issues/240

textOrientation -- direct mapping to CSS except the values: sidewaysLeft, sidewaysRight. These values should be replaced with "mixed"

fontKerning -- direct mapping to CSS

rubyReserve -- ignore

textCombine -- pending review by TTML2 group. Possibly direct mapping to CSS 

disparity -- ignore

textShadow -- direct mapping to CSS

origin -- how have implementers handled this with TTML1?

position -- direct mapping to CSS

initial -- need more info from fallback implementers. What are the challenges with initial?

**Comment by skynavga** [comment]
Fallbacks like this need to be coordinated with the definition of feature designators (in TTML2) that cover only the supported semantics.

**Comment by dae-kim** [comment]
Edited the title. The problem as I understand it is: some IMSC2 implementors will be unable to follow even the TTML2 defined fallbacks for certain attributes. 

For example, whatever fallback TTML2 defines for rubyReserve, a pure CSS implementation will be unable to honor it. So in this case, I propose the CSS-constrained implementer ignore rubyReserve altogether.

**Comment by skynavga** [comment]
On Tue, Mar 14, 2017 at 5:00 PM, dae-kim <notifications@github.com> wrote:

> Edited the title. The problem as I understand it is: some IMSC2
> implementors will be unable to follow even the TTML2 defined fallbacks for
> certain attributes.
>
> For example, whatever fallback TTML2 defines for rubyReserve, a pure CSS
> implementation will be unable to honor it. So in this case, I propose the
> CSS-constrained implementer ignore rubyReserve altogether.
>
That is the same thing as designating that feature to be optional. So that
means IMSC2 will need to specify a number of optional features, which is
different than IMSC1, which specifies that all referenced features are
required (to be supported).

**Comment by nigelmegitt** [comment]
> IMSC2 will need to specify a number of optional features, which is
different than IMSC1

The argument (whether you agree with it or not) for IMSC 1 was that if processors cannot be guaranteed to support a feature then authors shall not include them in documents, so that implementations generate consistent output. We can re-use the same argument, which would have the impact that, if CSS support is a requirement for IMSC2, then features of TTML2 that do not have a mapping to CSS are prohibited.

On the other hand, in IMSC 1.[0.]1 we are introducing optional features, on the basis that the fallback of non support remains acceptable. So on this basis IMSC2 could have optional features.

It would seem like a bad idea to make processor features optional if the fallback of non-support is unusable output, e.g. text that is not readable. So I would prioritise our focus on any features that have that footprint.

**Comment by dae-kim** [comment]
Would it help if we described this document as a how-to on transforming IMSC2 to HTML (or the like)?

There are cases today when a subtitle customer wants a TTML1 document converted to SCC or SRT.
In those cases, the challenge is to preserve as much authorial intent as possible while reasonably deprecating features that cannot be preserved.

So could we avoid optional features in IMSC2 by stating an IMSC2 processor must support the TTML2 semantics, but by the way, "here's a way to transform IMSC2 to HTML if needed"?

**Comment by nigelmegitt** [comment]
I've begun adding more detail on mapping of TTML2 style attributes to CSS on this [TTML wiki page](https://www.w3.org/wiki/index.php?title=TTML/CSSRequirements).

**Comment by nigelmegitt** [comment]
@dae-kim I notice that `tts:rubyOffset` and `tts:rubyOverhangClass` are missing from the list in https://github.com/w3c/imsc/issues/218#issuecomment-286582160 and therefore also from the [CSS Requirements wiki page](https://www.w3.org/wiki/TTML/CSSRequirements). Did you omit those deliberately because you don't expect us to need them in IMSC2 or was it an oversight?

**Comment by palemieux** [comment]
Propose to close in light of https://github.com/w3c/ttml2/issues/406 .

**Comment by nigelmegitt** [comment]
@palemieux Now that we have agreed to remove some styling extensions from TTML2 we should rescope this issue to the extension attributes only, and not close for now. For example describing how to map `ittp:fillLineGap` to CSS (or the difficulty in so doing).
