### ISSUE TITLE
Should ittp:progressivelyDecodable be deprecated?

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc#272]
Is it actively used? If so, addition to TTML2 should be considered.

**Comment by nigelmegitt** [comment]
This may be restating the issue, but I'm not clear about how `ittp:progressivelyDecodable` is used in practice. Are there implementations and streaming approaches that deliver TTML documents gradually, simultaneously with their presentation, so that presentation must begin before they are complete? 

I'm unaware of any such approach at the moment. For example, delivery in fragmented MP4 allows for a sequence of complete documents to be delivered, one per sample, so it would not need any sense of progressive decoding.

**Comment by palemieux** [comment]
Based on (private) feedback from folks involved in Ultraviolet, it sounds like the feature has not been used, and can safely be deprecated.
