### ISSUE TITLE
APA comment: richer semantic layers than forcedDisplay allows

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc#320]
From https://lists.w3.org/Archives/Public/public-tt/2018Jan/0270.html

Section 7.7.3 itts:forcedDisplay. This seems like a temporary solution. Wouldn’t it be better to define semantic layers of information that each could be made visible and invisible at runtime as appropriate for the user?  For example, the user may want to see either speech-only (subtitles), narration speech only (parts of subtitles), foreign-language speech-only (parts of subtitles) or any combination of them.

**Comment by palemieux** [comment]
`tts:forcedDisplay` is intended to address current distribution requirements: the ability to identify subtitles that should be displayed, e.g. translation of street signs, even if the user has not explicitly selected subtitles for display, e.g. because the user is content with dubbed audio.

TTML2 offers a more flexible conditional mechanism (`condition` attributes), which can be used in future versions of IMSC as new requirements emerge.

Furthermore, it might be that practice ultimately evolves towards expressing different presentation scenarios as alternate tracks, rather than a single track with multiple embedded choices.

**Comment by palemieux** [comment]
Proposed disposition: WR-reject
