### ISSUE TITLE
Add note to tts:position that negative offsets are not allowed

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc#367]
... since regions must be within the root container region

**Comment by nigelmegitt** [comment]
Why call out this particular possible way to create regions that are positioned partly outside the root container region? There are other permutations too, such as specifying an extent that is wider or taller than 100%, which we do not call out with a note.

I don't really mind an informative note, just a really tiny bit concerned that it might be misread as an enumeration of all the things that are prohibited, rather than only a single example.

**Comment by palemieux** [comment]
> I don't really mind an informative note, just a really tiny bit concerned that it might be misread as an
> enumeration of all the things that are prohibited, rather than only a single example.

Yes, I am not excited by all these notes. It was intended to match the third note at https://www.w3.org/TR/ttml-imsc1.0.1/#ittp-activeArea.

**Comment by nigelmegitt** [comment]
I think it's the other way around though, in that the third note you reference just describes a _result_ of the normative requirement, whereas adding a note about a particular set of values that is prohibited by the normative requirement, without being exhaustive, feels like a step too far for me.

Is this an external request? If it's wide review feedback I would like to know more about the reason for it. Otherwise I would say take no action and close this issue. Happy to hear other views of course.

**Comment by palemieux** [comment]
I created this issue on my own, and am happy to close it if no one else sees value in the proposed note.
