### ISSUE TITLE
Limit application of rw/rh tts:extent and tts:position

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc#445]
When horizontal relative lengths (`rw`) are used in vertical extent or position dimensions, or conversely when vertical relative lengths (`rh`) are used in horizontal extent or position dimensions, the determination of whether the region extend beyond the root container becomes dependent on the aspect ratio of the root container, which is not always available to the author.

Suggest prohibiting the application of horizontal relative lengths in a vertical context, and vice versa, when applied to `tts:extent` and `tts:position`.

See also https://github.com/w3c/imsc-tests/issues/77#issuecomment-417373785

**Comment by palemieux** [comment]
Such constraint is expected to be allowed without triggering another CR since `#length-root-container-relative` is at-risk

**Comment by nigelmegitt** [comment]
An alternative, editorial, approach here would be to add a note to point out that this usage is in this sense "dangerous" and that if the aspect ratio of the root container is unknown at authoring time then it's unwise to use it, and leave it to authors and implementers.

Question: @palemieux is your proposal to prohibit this use only when the aspect ratio is unknown, or always? Or to prohibit `rw` and `rh` units from `tts:extent` and `tts:position` altogether? The latter might be a logical conclusion from the fact that when defining region extent and position the `rw` and `rh` units are identical to `%` when used in the same-direction dimension. 

Question: How is the following text to be interpreted in the case that a region is somehow defined to be outside the root container region? The text is at https://www.w3.org/TR/ttml-imsc1.1/#region-dim-pos :

> All regions SHALL NOT extend beyond the Root Container Region, i.e. every coordinate in the set of coordinates of each region is also in the set of coordinates of the Root Container Region.

Does this mean A) that the specified region position and size shall not extend etc, i.e. it is intended to be a statement against which document instances can be validated? Or does it mean B) that regardless of what the document states, the processor shall clip the computed region to include only those coordinates in the root container region, at processing time?

If it is A, then we need to ensure that the constraint can actually be validated. If it is B, then in a sense the spec ensure some loose kind of safety, in that the constraint will be imposed, but the effect might not be what the author expected or intended.

**Comment by palemieux** [comment]
> Or to prohibit rw and rh units from tts:extent and tts:position altogether?

+1, that would be simplest.

> A) that the specified region position and size shall not extend etc, i.e. it is intended to be a statement against which
> document instances can be validated?

That has been my interpretation so far.

**Comment by nigelmegitt** [comment]
> That has been my interpretation so far.

We may need to tighten up the language editorially in that case, since I think either interpretation is possible now. Specifically, the constraint is on the computed sets of coordinates based on the specified origin/position and extent, and does not depend on some post-computation resolution to enforce the constraint, though of course players may wish to do such resolution as a form of error handling.

**Comment by palemieux** [comment]
> We may need to tighten up the language editorially in that case,

Ok. Do you have a suggestion?

> Or to prohibit rw and rh units from tts:extent and tts:position altogether?

Ok to proceed for an initial PR?

**Comment by nigelmegitt** [comment]
I could live with prohibiting `rw` and `rh` units on `position` and `extent` but it seems unfriendly to require authors to understand why they cannot use them here and they can for other places where they want a percentage of the root container region. 

My preference would instead be to constrain `rw` to horizontal coordinates and `rh` to vertical coordinates, so that a document need not contain `%` at all.

**Comment by nigelmegitt** [comment]
> Ok. Do you have a suggestion?

Add a note along the lines:

> Document instances can be validated with respect to this constraint by computing the coordinate sets from the specified location (`tts:origin` or `tts:position`) and size (`tts:extent`) of each region.

?

**Comment by palemieux** [comment]
> My preference would instead be to constrain rw to horizontal coordinates and rh to vertical coordinates,
> so that a document need not contain % at all.

`tts:origin` prohibits rh/rw, so I would think that prohibiting rh/rw on `tts:origin`, `tts:extent` and `tts:position` is easier for authors.

**Comment by nigelmegitt** [comment]
> I would think that prohibiting rh/rw on `tts:origin`, `tts:extent` and `tts:position` is easier for authors.

This seems to depend on where you start from, so it's a subjective call. 

When I consider an author setting font size and line height in terms of rw/rh, and wanting to size a region appropriately, I get to a different answer. For example "add 2 lines of centered text in an area 2 lines off the top, to occupy no more than 70% of the width, where each line is 8rh" results in `<region tts:position="top 16rh center" tts:extent="70rw 16rh" ...>` which is consistent with the style setting `tts:lineHeight="8rh"` and some font size that fits within that.

Hence I would rather stay as unrestrictive as possible while handling this corner case.

**Comment by palemieux** [comment]
> Hence I would rather stay as unrestrictive as possible while handling this corner case.

Ok. Can you propose text?

**Comment by nigelmegitt** [comment]
> Can you propose text?

Sure, at least a super-quick run through without exact wording (sorry, hitting time constraints on my day): 

* Add a new section to §7.12 after §7.12.8 titled `#length-root-container-relative` and reference it from the feature table for the Text Profile column.
* In that section, require that when `rw` and `rh` units are used for `tts:position` and `tts:extent` the `rw` unit must not be used for vertical length components and the `rh` unit must not be used for horizontal length components.
* In §7.12.1.2 add an editorial note pointing out that due to the constraint in [that new section] the constraint can be validated without regard to the aspect ratio of the root container region.
