### ISSUE TITLE
EnableRollUp doesn't works 

### ISSUE THREAD

**Issue by alex75020** [w3c/imsc#471]
Hello everyone, I would like to know how can I use enableRollUp parameter on a subtitle ? I am using Imcjs 1.0.2.   
I try to use it but it doesn't works...

**Comment by nigelmegitt** [comment]
Hi @alex75020 thank you for raising this question. You've asked this on the specification repository for the IMSC profiles of TTML.

The handling of [roll-up style presentation](https://www.w3.org/TR/2018/REC-ttml2-20181108/#semantics-smooth-scrolling-recommendation) is left to implementations by TTML2 and the IMSC profiles, and is certainly implemented in some presentation processors. Therefore this question probably needs to be directed towards the implementation you are using rather than here.

Therefore, and with apologies if this seems brusque, I'm going to close this issue directly.

**Comment by alex75020** [comment]
I understand exactly what do you mean, and its true..
 I will resolve it and i share it!
