### ISSUE TITLE
If I set a style attribute tts:fontSize="70%" instead of "100%", the fonts would overlap. 

### ISSUE THREAD

**Issue by fengliuxiaoxin** [w3c/imsc#576]
I found a problem:
I set a style attribute tts:fontSize="70%" instead of "100%", the fonts would overlap.  like the following pic:
![ttpi000001](https://user-images.githubusercontent.com/30992689/194693349-4ea3b41b-8699-407e-af4c-45c5d238cfd8.png)
How to set the fonts size 70% and make them not overlap. I didn't find this piece of code to fix it.
Would appreciate it if anyone could do me a fovar.

**Comment by nigelmegitt** [comment]
I'm not sure why this was opened and then closed? Feel free to reopen if there's an issue. Generally, reducing the font size does not cause the effect shown: I would speculate that it could be a font issue, since the font specifies the "advance" i.e. effectively the letter spacing. 

If it is not a font issue then it would be useful to see the document that generates this behaviour.
